# Generated by Django 3.2 on 2021-04-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cal',
            name='count',
            field=models.FloatField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
